export const projects = [
  {
    title: 'Burger Queen',
    image: 'assets/image/burgerQueen.png',
    demo: '',
    github: 'https://github.com/oriananohemi/BOG001-burger-queen',
  },
  {
    title: 'SolSalud',
    image: 'assets/image/solSalud.png',
    demo: 'https://oriananohemi.github.io/SolSalud/#/',
    github: 'https://github.com/oriananohemi/SolSalud',
  },
  {
    title: 'PetShop',
    image: 'assets/image/petShop.png',
    demo: '',
    github: 'https://github.com/oriananohemi/petShop',
  },
  {
    title: 'Buscador de Peliculas',
    image: 'assets/image/buscadorPeliculas.png',
    demo: 'https://oriananohemi.github.io/buscador-peliculas/',
    github: 'https://github.com/oriananohemi/buscador-peliculas',
  },
  {
    title: 'PhySport',
    image: 'assets/image/phySport.png',
    demo: 'https://oriananohemi.github.io/BOG001-social-network/',
    github: 'https://github.com/oriananohemi/BOG001-social-network',
  },
  {
    title: 'Pokedex',
    image: 'assets/image/pokedex.png',
    demo: 'https://oriananohemi.github.io/BOG001-data-lovers/',
    github: 'https://github.com/oriananohemi/BOG001-data-lovers',
  },
  {
    title: 'Twyno',
    image: 'assets/image/Twyno.png',
    demo: '',
    github: '',
  },
  {
    title: 'Tu Closet',
    image: 'assets/image/tuCloset.png',
    demo: 'https://oriananohemi.github.io/tuCloset/',
    github: 'https://github.com/oriananohemi/tuCloset',
  },
  {
    title: 'Pinterest',
    image: 'assets/image/pinterest.png',
    demo: '',
    github: '',
  },
  {
    title: 'PusheeCat',
    image: 'assets/image/pusheeCat.png',
    demo: 'https://oriananohemi.github.io/pusheenCat/',
    github: 'https://github.com/oriananohemi/pusheenCat',
  },
  // {
  //   title: 'Casa de Instrumentos',
  //   image: 'assets/image/casaDeInstrumento.png',
  //   demo: 'https://oriananohemi.github.io/Casa-de-Instrumentos/',
  //   github: 'https://github.com/oriananohemi/Casa-de-Instrumentos',
  // },
  {
    title: 'Instagram',
    image: 'assets/image/instagramPerfil.png',
    demo: 'https://oriananohemi.github.io/instagram/',
    github: 'https://github.com/oriananohemi/instagram',
  },
  {
    title: 'Instagram Home',
    image: 'assets/image/instagramHome.png',
    demo: 'https://oriananohemi.github.io/instagramHome/',
    github: 'https://github.com/oriananohemi/instagramHome',
  },
];
